#!/bin/sh
#
# Set hostname based on /etc/hostname 
#

case "$1" in
  start)
 	hostname -F /etc/hostname
	;;
  stop)
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo $"Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

