#!/bin/sh
#
# Mount all filesystems
#

case "$1" in
  start)
  	/bin/mount -t proc proc /proc
	/bin/mkdir -p /dev/pts
	;;
  stop)
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo $"Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

