#!/bin/sh
#
# Start the LEDs...
#

case "$1" in
  start)
 	echo "Starting heartbeat LED..."
  echo 'heartbeat' > /sys/class/leds/dockstar\:orange\:health/trigger
	;;
  stop)
	echo -n "Stopping heartbeat LED..."
  echo 'none' > /sys/class/leds/dockstar\:orange\:health/trigger
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo $"Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

