#!/bin/sh
#
# Turn off swap and umount all local file systems.
#

case "$1" in
  start)
	;;
  stop)
  	/bin/umount -a -r
  	/sbin/swapoff -a
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo $"Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

